[package]
name = "colorpicky"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async Runtime
embassy-executor = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "defmt",
    "time-driver",
    "critical-section-impl",
    "rp235xa",
] }
embassy-net = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "defmt",
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
] }

# WiFi Chip Communication
cyw43 = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "defmt",
    "firmware-logs",
] }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy", branch = "main", features = [
    "defmt",
] }

# Logging
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

# Cortex M
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.3"

# Display
embedded-graphics = "0.8"
st7735-lcd = "0.10"
embedded-hal-bus = "0.2"


# Fix for some linker issues
[profile.release]
debug = 1
lto = true
opt-level = 'z'
codegen-units = 1

[profile.dev]
debug = 1
lto = true
opt-level = "z"
